### ISSUE TITLE
PWA not working on Next 12

### ISSUE THREAD

**Issue by shivamCode0** [mvllow/next-pwa-template#19]
On Next.js version 12, the service worker does not install and there is an error in the console:
```
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://next-pwa-template.vercel.app/_next/server/middleware-manifest.json","status":404}]
    at Y.j (https://next-pwa-template.vercel.app/workbox-4a677df8.js:1:16755)
    at async Y.D (https://next-pwa-template.vercel.app/workbox-4a677df8.js:1:16353)
    at async Y.v (https://next-pwa-template.vercel.app/workbox-4a677df8.js:1:7595)
```

**Comment by mvllow** [comment]
Appreciate the report 😌 Looks like this is an upstream issue https://github.com/shadowwalker/next-pwa/issues/288

**Comment by mvllow** [comment]
This _may_ have been fixed by https://github.com/shadowwalker/next-pwa/pull/299
